services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: anomy
      POSTGRES_DB: normalizer
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - webnet
    restart: always
volumes:
  postgres: {}
networks:
  webnet:
